### ISSUE TITLE
[web] trim it down

### ISSUE THREAD

**Issue by idancali** [fluidtrends/chunky#171]
- [x] leave the bare minimum base screens
- [x] leave the bare minimum base components
- [x] make sure it all runs smooth
- [x] make sure the default template works well
- [x] prepare the rest to be reused in reusable chunks

Total deps size as of  now: **479M**

**Comment by idancali** [comment]
- the big ones:

- [ ] grpc
- [ ] antd
- [ ] firebase
- [ ] material

**Comment by idancali** [comment]
5.5M    node_modules/grpc/deps/grpc/third_party/boringssl/crypto
6.0M    node_modules/firebase
6.8M    node_modules/@babel
7.0M    node_modules/@ant-design/icons/lib
7.3M    node_modules/@firebase/polyfill
7.3M    node_modules/@firebase/polyfill/node_modules
7.3M    node_modules/@firebase/polyfill/node_modules/core-js
7.4M    node_modules/core-js
8.0M    node_modules/grpc/node_modules
8.2M    node_modules/grpc/deps/grpc/third_party/boringssl
8.3M    node_modules/react-savor/node_modules
8.5M    node_modules/react-savor
 10M    node_modules/antd/es
 10M    node_modules/antd/lib
 11M    node_modules/grpc/deps/grpc/third_party
 12M    node_modules/caniuse-db
 12M    node_modules/react-chunky/test
 13M    node_modules/@ant-design
 13M    node_modules/@ant-design/icons
 13M    node_modules/@rmwc
 15M    node_modules/@firebase
 15M    node_modules/react-chunky
 18M    node_modules/@material
 20M    node_modules/grpc/deps/grpc/src/boringssl
 25M    node_modules/grpc/deps/grpc/src
 36M    node_modules/grpc/deps
 36M    node_modules/grpc/deps/grpc
 40M    node_modules/antd/dist
 46M    node_modules/grpc
 61M    node_modules/antd

**Comment by aclowwwn** [comment]
We should pick between antd and material which one we'll use. I feel antd might be better (material had quite some issues in the past), but it's huuge.

**Comment by idancali** [comment]
- yeah agree on antd - working on trimming down the deps though - let's see how that feels
- but I also think that material has some things antd doesn't
- something to debate for sure :)

**Comment by idancali** [comment]
will be validated by this
https://github.com/fluidtrends/chunky/issues/174

**Comment by idancali** [comment]
needs this big time: https://github.com/fluidtrends/chunky/issues/175
